### ISSUE TITLE
Swap works from Solana, but not the other way?

### ISSUE THREAD

**Issue by craftfortress** [travis-bz/raydium-sdk-swap-no-mainnet.json-required#2]
Im sorry if I am being thick, but this code works perfect to buy tokenB, however I am unable to reverse the swap , it just keeps buying tokenB. If I change the tokenA <-> tokenB it fails to find the pair. Sorry for the silly question Im just totally confused. Thanks again for some good code tho!

**Comment by wicky-rx** [comment]
Hey Chris, you can swap tokens for SOL buy changing the direction to out.

**Comment by craftfortress** [comment]
Yep I spent time testing this and swapping the direction it keeps going in one direction - have you tested this to make sure the directions isn’t hardcoded? I’ll try again when I get home thanks

**Comment by craftfortress** [comment]
I had to make a few changes but I got it to work thanks for the cool code!
